# Basic Information 
title: Jiamin Cheng
position: Postgraduate Student
affiliation: Macau University of Science and Technology
affiliation_link: https://www.must.edu.mo/en
email: jiamincheng.k@gmail.com

# Search Engine Optimization (SEO)
keywords: jiamin cheng, jiamincheng, cheng jiamin, chengjiamin
description: Jiamin Cheng is a graduate student at the Macau University of Science and Technology. Her research interests include image enhancement and image generation.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
github_link: https://github.com/jiamincheng
cv_link: ./files/cjm_cv.pdf



# Images 
avatar: ./files/me.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
footnote: Feel free to use my website's source code.
footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: l3lesztPwCz-uXlzFI1Lt9SB3Ctz-pBQuMdYqnD0Ul8

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
