# Basic Information 
title: Jiamin Cheng(程佳敏)
position: PhD Student
affiliation: Binghamton University
affiliation_link: https://www.binghamton.edu/
email: jcheng18@binghamton.edu

# Search Engine Optimization (SEO)
keywords: jiamin cheng, jiamincheng, cheng jiamin, chengjiamin
description: A PhD student in Computer Science.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
github_link: https://github.com/jiamincheng




# Images 
avatar: ./files/me.jpg
favicon: ./files/me.jpg
favicon_dark: ./files/me.jpg



# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
