# Basic Information 
title: Jiamin Cheng            (程佳敏)
position: Postgraduate Student
affiliation: Macau University of Science and Technology
affiliation_link: https://www.must.edu.mo/en
email: jiamincheng.k@gmail.com

# Search Engine Optimization (SEO)
keywords: jiamin cheng, jiamincheng, cheng jiamin, chengjiamin
description: A graduate student at the Macau University of Science and Technology.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
github_link: https://github.com/jiamincheng
cv_link: ./files/cjm_cv.pdf



# Images 
avatar: ./files/me.jpg
favicon: ./files/me.jpg
favicon_dark: ./files/me.jpg



# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
